"""empty message

Revision ID: 1513ff3283f7
Revises: aa833583ade1
Create Date: 2023-11-28 14:42:48.289902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1513ff3283f7'
down_revision = 'aa833583ade1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncrs_table',
    sa.Column('NCRID', sa.Integer(), nullable=False),
    sa.Column('LocationID', sa.Integer(), nullable=True),
    sa.Column('Category', sa.String(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('WorkOrderNumber', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['LocationID'], ['location.LocationID'], name='fk_ncr_location'),
    sa.PrimaryKeyConstraint('NCRID')
    )
    op.drop_table('nc_rs_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nc_rs_table',
    sa.Column('NCRID', sa.INTEGER(), nullable=False),
    sa.Column('LocationID', sa.INTEGER(), nullable=True),
    sa.Column('Category', sa.VARCHAR(), nullable=True),
    sa.Column('Quantity', sa.INTEGER(), nullable=True),
    sa.Column('WorkOrderNumber', sa.INTEGER(), nullable=True),
    sa.Column('Description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['LocationID'], ['location.LocationID'], name='fk_ncr_location'),
    sa.PrimaryKeyConstraint('NCRID')
    )
    op.drop_table('ncrs_table')
    # ### end Alembic commands ###
