"""empty message

Revision ID: 6a5b6165c3fb
Revises: b1506001d5c3
Create Date: 2023-11-28 14:38:33.831760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5b6165c3fb'
down_revision = 'b1506001d5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'location', ['LocationID'], ['LocationID'])

    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'location', ['LocationID'], ['LocationID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
