"""changing location to go to location table

Revision ID: a388b6dee666
Revises: fcaaff9c13cb
Create Date: 2023-11-28 14:33:09.895199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a388b6dee666'
down_revision = 'fcaaff9c13cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('LocationID')

    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'location', ['LocationID'], ['LocationID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LocationID', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
