"""empty message

Revision ID: aa833583ade1
Revises: 6a5b6165c3fb
Create Date: 2023-11-28 14:39:59.395257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa833583ade1'
down_revision = '6a5b6165c3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_machine_location', 'location', ['LocationID'], ['LocationID'])

    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ncr_location', 'location', ['LocationID'], ['LocationID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ncr_location', type_='foreignkey')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_machine_location', type_='foreignkey')

    # ### end Alembic commands ###
