"""empty message

Revision ID: c091841dda57
Revises: a388b6dee666
Create Date: 2023-11-28 14:36:29.684249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c091841dda57'
down_revision = 'a388b6dee666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_machines')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('LocationID')

    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'location', ['LocationID'], ['LocationID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nc_rs_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LocationID', sa.INTEGER(), nullable=True))

    op.create_table('_alembic_tmp_machines',
    sa.Column('MachineID', sa.INTEGER(), nullable=False),
    sa.Column('MachineSerial', sa.INTEGER(), nullable=True),
    sa.Column('MachineName', sa.VARCHAR(length=50), nullable=True),
    sa.Column('MachineAlias', sa.VARCHAR(length=50), nullable=True),
    sa.Column('MachineType', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('MachineID')
    )
    # ### end Alembic commands ###
