from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func
from sqlalchemy import func



class PowderBlends(db.Model):
    PowderBlendPartID = db.Column(db.Integer, primary_key=True, nullable=False) 
    PowderBlendID = db.Column(db.Integer)
    OldPowderBlendID = db.Column(db.Integer)
    AddedWeight = db.Column(db.Float)
    DateAdded = db.Column(db.DateTime(timezone=True),default=func.now())
    PowderInventoryBatchID = db.Column(db.Integer)
  

class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(50))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))



class InventoryVirginBatch(db.Model):
    VirginID = db.Column(db.Integer, primary_key=True, nullable=False) 
    BatchID	= db.Column(db.Integer) 
    VirginPO = db.Column(db.Integer)	
    VirginLot = db.Column(db.String)	
    Supplier = db.Column(db.String)	
    VirginQty = db.Column(db.Float)	
    MaterialID	= db.Column(db.Integer)
    BatchName = db.Column(db.String)
    BatchCreatedBy = db.Column(db.String)
    BatchTimeStamp = db.Column(db.DateTime(timezone=True),default=func.now())


class Builds(db.Model):
    buildID = db.Column(db.Integer, primary_key=True)
    createdBy = db.Column(db.String(50))
    createdOn = db.Column(db.Date)
    facilityName = db.Column(db.String(50))
    solidJobsBuildID = db.Column(db.Integer)
    material = db.Column(db.String(50))
    machine = db.Column(db.String(50))
    buildName = db.Column(db.String(50))
    platformWeight = db.Column(db.Float)
    layer = db.Column(db.Float)
    height = db.Column(db.Float)
    offset = db.Column(db.Float)
    scaleX = db.Column(db.Float)
    scaleY = db.Column(db.Float)
    note = db.Column(db.String(255))
    buildStart = db.Column(db.Date)
    buildFinish = db.Column(db.Date)
    buildTime = db.Column(db.Float)
    finishHeight = db.Column(db.Float)
    finishPlatformWeight = db.Column(db.Float)
    batch = db.Column(db.String(50))
    certificationBuild = db.Column(db.String(50))
    feedPowderHeight = db.Column(db.Float)
    endFeedPowderHeight = db.Column(db.Float)
    potentialBuildHeight = db.Column(db.Float)
    location = db.Column(db.String(50))
    plateThickness = db.Column(db.Float)
    plateSerial = db.Column(db.String(50))
    MinChargeAmount = db.Column(db.Float)
    MaxChangeAmount = db.Column(db.Float)
    DosingBoostAmount = db.Column(db.Float)
    RecoaterSpeed = db.Column(db.Float)
    ParameterRev = db.Column(db.String(50))
    MeasuredLaserPower = db.Column(db.Float)
    GasFlow = db.Column(db.Float)
    MaterialAdded = db.Column(db.Float)
    InitialDosingFactor = db.Column(db.Float)
    MaxFinishHeight = db.Column(db.Float)
    MaxBuildTime = db.Column(db.Integer)
    MaxDateDifference = db.Column(db.Integer)
    platformTemperature = db.Column(db.Float)
    startLaserHours = db.Column(db.Float)
    finalLaserHours = db.Column(db.Float)
    InertTime = db.Column(db.Date)
    F9FilterSerial = db.Column(db.String(50))
    H13FilterSerial = db.Column(db.String(50))
    FilterLight = db.Column(db.String(50))
    EndPartPistonHeight = db.Column(db.Float)
    Breakout = db.Column(db.String(50))
    CompletedWithoutStoppage = db.Column(db.String(50))
    Humidity = db.Column(db.Float)
    BuildInterrupts = db.Column(db.String(50))
    RecoaterType = db.Column(db.String(50))
    VeloFlowSoftwareRev = db.Column(db.String(50))
    VeloFlowSoftwareBase = db.Column(db.String(50))
    VeloFlowBuildTimeEstimation = db.Column(db.Integer)
    VeloFlowBuildTimeEstimationCore = db.Column(db.Integer)
    VeloFlowBuildTimeEstimationSkin = db.Column(db.Integer)
    VeloFlowBuildTimeEstimationSupport = db.Column(db.Integer)
    VeloFlowBuildTimeEstimationRecoater = db.Column(db.Integer)
    VeloPrintSWRev = db.Column(db.String(50))
    SieveChange = db.Column(db.String(50))
    LayerCount = db.Column(db.Integer)
    FilterChange = db.Column(db.String(50))
    BeamStabilityTestPerformed = db.Column(db.String(50))
    LaserAlignmentTestPerformed = db.Column(db.String(50))
    ThermalSensorTest = db.Column(db.String(50))
    LaserFocus = db.Column(db.String(50))
    PowderBed = db.Column(db.String(50))
    PowderLevel = db.Column(db.String(50))
    SieveLife = db.Column(db.Integer)
    FilterPressureDrop = db.Column(db.Float)


